"""Export the AI-generated report in multiple formats."""

from __future__ import annotations
import io
import json
import zipfile
from datetime import datetime
from dataclasses import asdict
from pathlib import Path

from markdown_pdf import MarkdownPdf, Section


def build_markdown(
    report_md: str,
    source_name: str,
) -> bytes:
    """Wrap the report in a nice header + footer and return as bytes."""
    header = f"# Vera.AI Analysis Report\n\n"
    header += f"**Dataset:** `{source_name}`  \n"
    header += f"**Generated:** {datetime.now().strftime('%B %d, %Y at %H:%M')}  \n\n"
    header += "---\n\n"

    footer = "\n\n---\n\n*Generated by Vera.AI — analysis you can cite.*\n"
    return (header + report_md + footer).encode("utf-8")


def build_pdf(report_md: str, source_name: str) -> bytes:
    """Convert the report to a PDF and return as bytes."""
    pdf = MarkdownPdf(toc_level=2)

    header = f"# Vera.AI Analysis Report\n\n"
    header += f"**Dataset:** `{source_name}`  \n"
    header += f"**Generated:** {datetime.now().strftime('%B %d, %Y at %H:%M')}  \n"

    footer = "\n\n---\n\n*Generated by Vera.AI — analysis you can cite.*"

    full_md = header + "\n---\n\n" + report_md + footer

    css = """
    body { font-family: -apple-system, 'Segoe UI', sans-serif; color: #1A1A1A; line-height: 1.55; }
    h1 { color: #0E5C4A; border-bottom: 2px solid #D97757; padding-bottom: 0.3em; }
    h2 { color: #0E5C4A; margin-top: 1.5em; }
    h3 { color: #0E5C4A; }
    code { background: #F3F1EA; padding: 2px 5px; border-radius: 3px; font-size: 0.9em; }
    em { color: #6B6B6B; }
    """
    pdf.add_section(Section(full_md), user_css=css)

    buf = io.BytesIO()
    pdf.save(buf)
    buf.seek(0)
    return buf.getvalue()


def build_bundle_zip(
    report_md: str,
    source_name: str,
    analysis_context: dict,
    charts: list | None = None,
) -> bytes:
    """Build a zip with: report.md, report.pdf, analysis.json, and chart PNGs."""
    buf = io.BytesIO()
    base_name = Path(source_name).stem

    with zipfile.ZipFile(buf, "w", zipfile.ZIP_DEFLATED) as zf:
        # Markdown report
        zf.writestr(f"{base_name}_report.md", build_markdown(report_md, source_name))

        # PDF report
        try:
            zf.writestr(f"{base_name}_report.pdf", build_pdf(report_md, source_name))
        except Exception as e:
            zf.writestr("pdf_error.txt", f"PDF generation failed: {e}")

        # Raw analysis as JSON (for programmatic use)
        zf.writestr(
            f"{base_name}_analysis.json",
            json.dumps(analysis_context, indent=2, default=str),
        )

        # Charts as PNG
        if charts:
            for i, chart in enumerate(charts):
                try:
                    png_bytes = chart.figure.to_image(format="png", width=1200, height=600)
                    safe_title = "".join(c if c.isalnum() or c in "._- " else "_" for c in chart.title)
                    zf.writestr(f"charts/{i:02d}_{safe_title}.png", png_bytes)
                except Exception:
                    # Chart export needs kaleido; skip if unavailable
                    pass

    buf.seek(0)
    return buf.getvalue()


def timestamp() -> str:
    """UTC timestamp suitable for filenames."""
    return datetime.now().strftime("%Y%m%d_%H%M%S")